"""Catalogo local de itens usados pelo bot e pela planilha da API."""

WEAPONS = [
    "Arco do",
    "Arco longo",
    "Arco de Guerra",
    "Besta do",
    "Besta Pesada",
    "Besta Leve",
    "Machado de Guerra",
    "Machadão",
    "Alabarda",
    "Adaga do",
    "Par de Adagas",
    "Garras do",
    "Martelo do",
    "Martelo Elevado",
    "Martelo de Batalha",
    "Luvas de Lutador",
    "Braçadeiras de Batalha",
    "Manoplas Cravadas",
    "Bordão do",
    "Cajado Férreo",
    "Cajado Bilaminado",
    "Lança do",
    "Pique",
    "Archa",
    "Espada Larga",
    "Montante",
    "Espadas Duplas",
    "Cajado Arcano do",
    "Cajado Arcano Elevado",
    "Cajado Enigmático",
    "Cajado Amaldiçoado",
    "Cajado Amaldiçoado Elevado",
    "Cajado Demoníaco",
    "Cajado de Fogo do",
    "Cajado de Fogo Elevado",
    "Cajado Infernal",
    "Cajado de Gelo do",
    "Cajado de Gelo Elevado",
    "Cajado Glacial",
    "Cajado Sagrado do",
    "Cajado Sagrado Elevado",
    "Cajado Divino",
    "Cajado da Natureza do",
    "Cajado da Natureza Elevado",
    "Cajado Selvagem",
    "Tomo de Feitiços",
    "Tocha do",
    "Escudo do",
]

ARMORS = [
    "Robe de Erudito",
    "Robe de Clérigo",
    "Robe de Mago",
    "Robe de Druida",
    "Casaco de Mercenário",
    "Casaco de Caçador",
    "Casaco de Assassino",
    "Casaco de Espreitador",
    "Armadura de Soldado",
    "Armadura de Cavaleiro",
    "Armadura de Guardião",
    "Armadura de Guarda-tumbas",
    "Capote de Erudito",
    "Capote de Clérigo",
    "Capote de Mago",
    "Capote de Druida",
    "Capuz de Mercenário",
    "Capuz de Caçador",
    "Capuz de Assassino",
    "Capuz de Espreitador",
    "Elmo de Soldado",
    "Elmo de Cavaleiro",
    "Elmo de Guardião",
    "Elmo de Guarda-tumbas",
    "Sandálias de Erudito",
    "Sandálias de Clérigo",
    "Sandálias de Mago",
    "Sandálias de Druida",
    "Sapatos de Mercenário",
    "Sapatos de Caçador",
    "Sapatos de Assassino",
    "Sapatos de Espreitador",
    "Botas de Soldado",
    "Botas de Cavaleiro",
    "Botas de Guardião",
    "Botas de Guarda-tumbas",
    "Capa",
    "Bolsa",
]

ITEM_API_BASE_IDS = {
    "Arco do": "2H_BOW",
    "Arco longo": "2H_LONGBOW",
    "Arco de Guerra": "2H_WARBOW",
    "Besta do": "2H_CROSSBOW",
    "Besta Pesada": "2H_CROSSBOWLARGE",
    "Besta Leve": "MAIN_1HCROSSBOW",
    "Machado de Guerra": "MAIN_AXE",
    "Machadão": "2H_AXE",
    "Alabarda": "2H_HALBERD",
    "Adaga do": "MAIN_DAGGER",
    "Par de Adagas": "2H_DAGGERPAIR",
    "Garras do": "2H_CLAWPAIR",
    "Martelo do": "MAIN_HAMMER",
    "Martelo Elevado": "2H_HAMMER",
    "Martelo de Batalha": "2H_POLEHAMMER",
    "Luvas de Lutador": "2H_KNUCKLES_SET1",
    "Braçadeiras de Batalha": "2H_KNUCKLES_SET2",
    "Manoplas Cravadas": "2H_KNUCKLES_SET3",
    "Bordão do": "2H_QUARTERSTAFF",
    "Cajado Férreo": "2H_IRONCLADEDSTAFF",
    "Cajado Bilaminado": "2H_DOUBLEBLADEDSTAFF",
    "Lança do": "MAIN_SPEAR",
    "Pique": "2H_SPEAR",
    "Archa": "2H_GLAIVE",
    "Espada Larga": "MAIN_SWORD",
    "Montante": "2H_CLAYMORE",
    "Espadas Duplas": "2H_DUALSWORD",
    "Cajado Arcano do": "MAIN_ARCANESTAFF",
    "Cajado Arcano Elevado": "2H_ARCANESTAFF",
    "Cajado Enigmático": "2H_ENIGMATICSTAFF",
    "Cajado Amaldiçoado": "MAIN_CURSEDSTAFF",
    "Cajado Amaldiçoado Elevado": "2H_CURSEDSTAFF",
    "Cajado Demoníaco": "2H_DEMONICSTAFF",
    "Cajado de Fogo do": "MAIN_FIRESTAFF",
    "Cajado de Fogo Elevado": "2H_FIRESTAFF",
    "Cajado Infernal": "2H_INFERNOSTAFF",
    "Cajado de Gelo do": "MAIN_FROSTSTAFF",
    "Cajado de Gelo Elevado": "2H_FROSTSTAFF",
    "Cajado Glacial": "2H_GLACIALSTAFF",
    "Cajado Sagrado do": "MAIN_HOLYSTAFF",
    "Cajado Sagrado Elevado": "2H_HOLYSTAFF",
    "Cajado Divino": "2H_DIVINESTAFF",
    "Cajado da Natureza do": "MAIN_NATURESTAFF",
    "Cajado da Natureza Elevado": "2H_NATURESTAFF",
    "Cajado Selvagem": "2H_WILDSTAFF",
    "Tomo de Feitiços": "OFF_BOOK",
    "Tocha do": "OFF_TORCH",
    "Escudo do": "OFF_SHIELD",
    "Robe de Erudito": "ARMOR_CLOTH_SET1",
    "Robe de Clérigo": "ARMOR_CLOTH_SET2",
    "Robe de Mago": "ARMOR_CLOTH_SET3",
    "Robe de Druida": "ARMOR_CLOTH_KEEPER",
    "Casaco de Mercenário": "ARMOR_LEATHER_SET1",
    "Casaco de Caçador": "ARMOR_LEATHER_SET2",
    "Casaco de Assassino": "ARMOR_LEATHER_SET3",
    "Casaco de Espreitador": "ARMOR_LEATHER_MORGANA",
    "Armadura de Soldado": "ARMOR_PLATE_SET1",
    "Armadura de Cavaleiro": "ARMOR_PLATE_SET2",
    "Armadura de Guardião": "ARMOR_PLATE_SET3",
    "Armadura de Guarda-tumbas": "ARMOR_PLATE_UNDEAD",
    "Capote de Erudito": "HEAD_CLOTH_SET1",
    "Capote de Clérigo": "HEAD_CLOTH_SET2",
    "Capote de Mago": "HEAD_CLOTH_SET3",
    "Capote de Druida": "HEAD_CLOTH_KEEPER",
    "Capuz de Mercenário": "HEAD_LEATHER_SET1",
    "Capuz de Caçador": "HEAD_LEATHER_SET2",
    "Capuz de Assassino": "HEAD_LEATHER_SET3",
    "Capuz de Espreitador": "HEAD_LEATHER_MORGANA",
    "Elmo de Soldado": "HEAD_PLATE_SET1",
    "Elmo de Cavaleiro": "HEAD_PLATE_SET2",
    "Elmo de Guardião": "HEAD_PLATE_SET3",
    "Elmo de Guarda-tumbas": "HEAD_PLATE_UNDEAD",
    "Sandálias de Erudito": "SHOES_CLOTH_SET1",
    "Sandálias de Clérigo": "SHOES_CLOTH_SET2",
    "Sandálias de Mago": "SHOES_CLOTH_SET3",
    "Sandálias de Druida": "SHOES_CLOTH_KEEPER",
    "Sapatos de Mercenário": "SHOES_LEATHER_SET1",
    "Sapatos de Caçador": "SHOES_LEATHER_SET2",
    "Sapatos de Assassino": "SHOES_LEATHER_SET3",
    "Sapatos de Espreitador": "SHOES_LEATHER_MORGANA",
    "Botas de Soldado": "SHOES_PLATE_SET1",
    "Botas de Cavaleiro": "SHOES_PLATE_SET2",
    "Botas de Guardião": "SHOES_PLATE_SET3",
    "Botas de Guarda-tumbas": "SHOES_PLATE_UNDEAD",
    "Capa": "CAPE",
    "Bolsa": "BAG",
}


def get_category_items():
    return {
        "armas": list(WEAPONS),
        "armaduras": list(ARMORS),
    }


def build_api_item_id(item_name, tier, enchantment):
    """Converte nome/tier/encantamento local para o UniqueName da API."""
    base_id = ITEM_API_BASE_IDS.get(item_name)
    if not base_id:
        return None

    item_id = f"{tier}_{base_id}"
    enchantment_number = str(enchantment).replace(".", "")
    if enchantment_number and enchantment_number != "0":
        item_id = f"{item_id}@{enchantment_number}"
    return item_id
